spring:
  datasource:
    meal:
      driverClassName: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://106.12.131.204:3306/meal?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2b8
      username: root
      password: '!@#qwe123'