spring:
  datasource:
    meal:
      driverClassName: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://106.13.198.47:3306/meal?useUnicode=true&amp&characterEncoding=utf-8
      username: root
      password: '!@#qwe123'