server:
  port: 8088
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10000000
      max-request-size: 10000000
      max-http-post-size: 102400000
      max-http-header-size: 102400000
  application:
    name: meal-operation
  profiles:
    active: db
  task:
    scheduling:
      pool:
        size: 50
